### ISSUE TITLE
Please add version numbers to library names

### ISSUE THREAD

**Issue by nlohmann** [Loki-Astari/JsonBenchmark#1]
Many libraries are in constant development, and it would be helpful to know which version was benchmarked.

**Comment by Loki-Astari** [comment]
I agree.

But I don't want to spend time hunting down something that is unique in each library and then hope the developer keeps the method consistent between versions. It would be better if there was some way to standardize and automate the processes through git hub. I choose "Last Commit Date" as a proxy for this value in the current release.

If you have a an alternative suggestion.
I could see if there is a tag on the current release? The trouble is that if I have a version that is not explicitly tagged that may not work well. Alternatively I could add an API the the class (but that would require each of the authors to be involved (to make sure I pick up the correct tag they use for versioning).

Any suggestions?


Martin (Aka Loki)

**Comment by nlohmann** [comment]
Using tags could be really the best automated way. For commit `eb7376b` of nlohmann/json,

```sh
git describe --contains eb7376b
```

returns `v3.9.0~43` which gives a better hint than just the hash.

**Comment by Loki-Astari** [comment]
I can definitely make a best effort attempt to obtain the tag.

The trouble here it relies on authors of these libraries making sure I know when to update there versions (if I just randomly pick up the current version it may not be explicitly tagged).

**Comment by nlohmann** [comment]
I don't think just picking "the last" commit is a good idea for a benchmark. I think choosing a version that was deemed as a proper release (and hence, tagged) by the authors is a better approach. For nlohmann/json, you actually pulled a commit from the develop branch which makes no guarantees about stability or performance.

**Comment by Loki-Astari** [comment]
The reason `nlohmann/json` is on a development branch is I found that latest commit of the default branch for all libraries (I assumed that the default branch is the one author wants people to use). Your default branch is "develop".

I will of course update now to the current master branch.

**Comment by nlohmann** [comment]
It was just an example. It could be much easier if you just pulled the latest release tag for all libraries.

**Comment by Loki-Astari** [comment]
I am unfamiliar how to pull the latest release tag.

**Comment by Loki-Astari** [comment]
```git describe --tags `git rev-list --tags --max-count=1````

**Comment by Loki-Astari** [comment]
Done

**Comment by nlohmann** [comment]
Thank you!
