### ISSUE TITLE
Can you share what build error you are getting with Glaze on Linux?

### ISSUE THREAD

**Issue by stephenberry** [Loki-Astari/JsonBenchmark#14]
I've had lots of trouble trying to configure this project. Can you share what build error you are getting with Glaze on Linux?

**Comment by RealTimeChris** [comment]
I've gotten it to run under linux on my fork of this repo.

**Comment by stephenberry** [comment]
Sweet!

**Comment by Loki-Astari** [comment]
Hey guys.

**Comment by Loki-Astari** [comment]
Merged the latest pull request.
Thanks for the work.
