### ISSUE TITLE
Cleaner Glaze usage

### ISSUE THREAD

**Issue by stephenberry** [Loki-Astari/JsonBenchmark#16]
I noticed you're using Glaze like this:
```c++
auto result = glz::read_json<std::vector<double>>(json);
if (result) {
   std::vector<double> data;
   data = std::move(result.value());
```

But, you can just do this:
```c++
std::vector<double> data;
auto error_code = glz::read_json(data, json);
```

This avoids the move and results in cleaner code.

**Comment by Loki-Astari** [comment]
I'll fix tonight.

**Comment by Loki-Astari** [comment]
OK. I see it.

I have fixed to the above style.
I would note that this was only done on the conformance tests (not performance).
The performance code already used the style indicated.

BUT: It is now all the same (or will be soon).
