### ISSUE TITLE
Issue with simdjson usage.

### ISSUE THREAD

**Issue by RealTimeChris** [Loki-Astari/JsonBenchmark#18]
I've just noticed that with your usage of simdjson - it looks as though you're not actually parsing the data into the eventual structures, but just running "stage-1" parsing as they call it. Here:
https://github.com/RealTimeChris/JsonBenchmark/blob/master/src/ThirdParty/simdjsonOndemandTest.cpp#L159-L167

**Comment by Loki-Astari** [comment]
I'll take a look tonight.

**Comment by RealTimeChris** [comment]
I think I've mostly fixed it in my fork of the repo. Checking the results now.

**Comment by Loki-Astari** [comment]
I will have a look today.

**Comment by RealTimeChris** [comment]
Thanks.

**Comment by RealTimeChris** [comment]
It's in the PR I made.
