### ISSUE TITLE
Stats table: duplicate column "FirstCommit"

### ISSUE THREAD

**Issue by nlohmann** [Loki-Astari/JsonBenchmark#2]
In the stats table (https://lokiastari.com/Json/Stats.html), there are two columns named "FirstCommit":

<img width="506" alt="Screen Shot 2020-07-25 at 22 07 43" src="https://user-images.githubusercontent.com/159488/88465458-56e4c800-cec3-11ea-8a49-3a7046a29d9c.png">

I guess the second one should be "MostRecentCommit" or something similar.

**Comment by Loki-Astari** [comment]
Ooops.
I'll fix that.

**Comment by Loki-Astari** [comment]
Done
